server:
  port: 9090

spring:
  application:
    name: service-consumer


eureka:
  client:
    register-with-eureka: false
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: http://root:123456@localhost:8761/eureka/,http://root:123456@localhost:8762/eureka/